language: node_js
node_js:
  - "stable"
before_install: cd API/
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql
env:
  global:
    - NODE_ENV=test
before_script:
  - psql -c 'create database betachop;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
  - npm run build
  - npm install -g sequelize-cli
  - sequelize db:migrate
  - sequelize db:seed:all
script:
  - npm test
after_success:
  - npm run coverage
