const actionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  GET_USER_MENU: 'GET_USER_MENU', // caterer action start
  ADD_TO_MENU: 'ADD_TO_MENU',
  GET_MENU_OPTIONS: 'GET_MENU_OPTIONS',
  ADD_MEAL: 'ADD_MEAL',
  EDIT_MEAL: 'EDIT_MEAL',
  DELETE_MEAL: 'DELETE_MEAL',
  GET_ORDER_HISTORY: 'GET_ORDER_HISTORY', // user action starts
  GET_TODAY_MENU: 'GET_TODAY_MENU',
  ORDER_MEAL: 'ORDER_MEAL',
  GET_USER_ORDER: 'GET_USER_ORDER',
  EDIT_ORDER: 'EDIT_ORDER', // user action ends
};

export default actionTypes;
